name: Test and Build Ktor project

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set executable permissions for gradlew
      run: chmod +x ./gradlew

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: 19

    - name: Build with Gradle
      run: ./gradlew build
