name: Test and Build Ktor project

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: 19
        distribution: temurin
        cache: 'gradle'
    
    - name: Set executable permissions for gradlew
      run: chmod +x ./gradlew

    - name: Test project
      run: ./gradlew test

    - name: Build project
      run: ./gradlew build
