name: Release KeyFusion Ktor project

on: workflow_dispatch

jobs:
  build:
    name: 'Build the project and create .jar file for Server'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 19
        distribution: temurin
        cache: 'gradle'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test build
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          ./build/libs/com.codecraft.ai.api-all.jar
